package me.lookforfps.oja.chatcompletion.model.natives.message;

import lombok.Data;
import lombok.NoArgsConstructor;
import me.lookforfps.oja.chatcompletion.model.natives.content.ContentList;
import me.lookforfps.oja.chatcompletion.model.natives.toolcall.ToolCall;

import java.util.List;

@Data
@NoArgsConstructor
public class Message {

    /**
     * <b>Description: </b>
     * The role of the author of this message.
     */
    private String role;
    /**
     * <b>Description: </b>
     * An array of content parts with a defined type, each can be of type <code>text</code> or <code>image_url</code> when passing in images.
     * You can pass multiple images by adding multiple <code>image_url</code> content parts.
     * Image input is only supported when using the <code>gpt-4-visual-preview</code> model.
     */
    private ContentList content;
    /**
     * <b>Description: </b>
     * An optional name for the participant. Provides the model information to differentiate between participants of the same role.
     */
    private String name;
    /**
     * <b>Description: </b>
     * The tool calls generated by the model, such as function calls.
     */
    private List<ToolCall> tool_calls;
    /**
     * <b>Description: </b>
     * Tool call that this message is responding to.
     */
    private String tool_call_id;

    public Message(String role, ContentList content) {
        this.role = role;
        this.content = content;
    }
}
